server:
  port: 7003
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VioletSY/service-config.git
          username: VioletSY
          password: sysy1023.
          search-paths: config
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

